version: '2'

services:

  web:
    build:
      context: .
    container_name: django
    restart: always
    env_file:
      - .env
#    command: bash -c "
#      python manage.py collectstatic --noinput &&
#      python manage.py makemigrations &&
#      python manage.py migrate &&
#      gunicorn shponchenroi.wsgi -b 0.0.0.0:8000 --reload"
    depends_on:
      - postgres
    links:
      - postgres
      - redis
    volumes:
      - .:/src
    expose:
      - "8000/tcp"
    ports:
      - "8000:8000"

  postgres:
    container_name: postgres
    restart: always
    build: ./config/postgres
    volumes:
      - postgresdatavolume:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432/tcp"

  redis:
    image: redis:latest
    hostname: redis

volumes:
  postgresdatavolume:
    driver: local